### ISSUE TITLE
S3NioSpiConfiguration constructor with overrides converts items to Strings

### ISSUE THREAD

**Issue by tony-johnson** [stefanofornari/aws-java-nio-spi-for-s3#3]
S3NioSpiConfiguration can store objects, such as AwsCredentials. But the constructor:

public S3NioSpiConfiguration(Map<String, ?> overrides)

converts the overrides values to strings (for no good reason I can see). This destroys the AwsCredentials when they are included in an S3NioSpiConfiguration passed to the FileSystems.newFileSystem. I think the fix is trivial:

-        overrides.keySet().forEach(key -> put(key, String.valueOf(overrides.get(key))));
+        overrides.keySet().forEach(key -> put(key, overrides.get(key)));

although perhaps the value should be cloned in case it is changed after insertion?

**Comment by stefanofornari** [comment]
@tony-johnson , good point. I will have a look at it. I am not a big fan of cloning, which then brings in all issues with serialization, but the conversion to string is definitely a left over.
