### ISSUE TITLE
Support for forcePathStyle true

### ISSUE THREAD

**Issue by tony-johnson** [stefanofornari/aws-java-nio-spi-for-s3#5]
In order to make this library work with my minio server I had to insert the following in S3ClientProvider

        //TODO: This should be controlled by configuration
        asyncClientBuilder.forcePathStyle(Boolean.TRUE);

Use of the AWS s3 code with a minio server requires this option be set to true. Perhaps better would be to include this as an option in 

S3NioSpiConfiguration 

perhaps

S3NioSpiConfiguration.withForcePathStyle(boolean value)

**Comment by stefanofornari** [comment]
Hi @tony-johnson,
thanks for pointing this out. This relates to this discussion: https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/115
and I want to address it as soon as we embed the support of 3rd party services into the official library. Stay tuned

**Comment by stefanofornari** [comment]
The way I would approach it is as follows:

1. add a new boolean config property s3.spi.force-path-style
2. if defined asyncClientBuilder.forcePathStyle(value); will be set
3. if not defined nothing is set for the s3 provider, it defaults to true for s3x provider
